# Custom configuration for scss linting

linters:
  Indentation:
    character: tab
    width: 1

  PropertySortOrder:
    order: concentric
    separate_groups: true

  LeadingZero:
    style: include_zero

  Compass::*:
    enabled: true

  StringQuotes: false
